site_name: 税制ガイド
site_description: 私的年金制度と節税制度のまとめ
theme:
  name: mkdocs
nav:
  - ホーム: index.md
  - DC制度解説: DC制度解説.md
  - 各制度:
      - DCマッチング拠出: dc-matching.md
      - iDeCo: ideco.md
      - 小規模企業共済: shokibo-kyosai.md
  - その他税制:
      - 所得税の基本: tax-income.md
      - 住民税の基本: tax-resident.md
      - 所得控除:
          - 基礎控除: deduction-basic.md
          - 社会保険料控除: deduction-social-insurance.md
          - 医療費控除: deduction-medical.md
          - 配偶者控除・扶養控除: deductions-family.md
          - 生命保険料控除等: deduction-insurance.md
      - 税額控除:
          - 住宅ローン控除: credits-housing-loan.md
          - 寄附金税額控除（ふるさと納税）: deduction-donation.md
markdown_extensions:
  - admonition
  - toc
  - tables
  - footnotes
