site_name: 税制ガイド
site_description: 私的年金制度と節税制度のまとめ
site_dir: web/mkdocs
theme:
  name: mkdocs
nav:
  - 計算ツールへ戻る: '../..'
  - ホーム: index.md
  - DC制度解説: DC制度解説.md
  - 各制度:
      - DCマッチング拠出: DCマッチング拠出.md
      - iDeCo: 個人型確定拠出年金_iDeCo.md
      - 小規模企業共済: 小規模企業共済.md
  - その他税制:
      - 所得税の基本: 所得税の基本.md
      - 住民税の基本: 住民税の基本.md
      - 所得控除:
          - 基礎控除: 基礎控除.md
          - 社会保険料控除: 社会保険料控除.md
          - 医療費控除: 医療費控除.md
          - 配偶者控除・扶養控除: 配偶者控除_扶養控除.md
          - 生命保険料控除等: 生命保険料控除等.md
      - 税額控除:
          - 住宅ローン控除: 住宅ローン控除.md
          - 寄附金税額控除（ふるさと納税）: 寄附金控除_ふるさと納税.md
markdown_extensions:
  - admonition
  - toc
  - tables
  - footnotes
