name: Deploy MkDocs to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MkDocs
        run: |
          pip install mkdocs
          pip install mkdocs-material
      - name: Build MkDocs site
        run: mkdocs build --site-dir web
      - uses: actions/configure-pages@v5
        with:
          enablement: true
      - uses: actions/upload-pages-artifact@v4
        with:
          path: web
      - uses: actions/deploy-pages@v4
